= Entwicklerdokumentation

== Einführung und Ziele
Die Internet-Plattform EMMA bietet ein breites Sortiment an Luxuswaren. Mittels Werben neuer Kunden kann jeder Kunde ein Rabattkonto füllen, um bei eigenen Einkäufen Rabatte zu erhalten. Der erfolgreichste Werber hat die Möglichkeit eine Kreuzfahrt zu gewinnen. 
Das Internet-Kaufhaus soll eine übersichtliche, anschauliche Website erhalten, welche dem Kunden eine klare Übersicht über alle Produkte gibt und einen einfachen Einkauf garantiert. Mitarbeiter und Administratoren sollen eine einfache Übersicht über die Informationen der Produkte und Kunden haben.

== Randbedingungen

=== Technische Randbedingungen

|===
|Betriebssystem |Linux
|Plattform |Webanwendung 
|Architektur |Frontend direkt im Web, Backend läuft auf dem Server einer Hosting-Agentur, Umsetzung des Backends erfolgt mit den Java-Frameworks „Spring“ und dem darauf aufgebauten „SalesPoint“, das Frostend wird mit „Bootstrab“ umgesetzt
|vergleichbare Projekte | http://www.karstadt.de, http://shop.kadewe.de
|===

=== Organisatorische Randbedingungen

|===
|Auftraggeber |Auftraggeber für den Online-Shop ist die EMMA AG
|Auftragnehmer | Die Entwicklung des Front- und Backends erfolgt von TEAM22
|Projektbudget | 500 D-Mark
|Haftung | TEAM22 übernimmt keinerlei Haftung
|Zeitplan |Endabgabe des Projektes ist im Februar 2016 
|Betrieb | Der Betrieb erfolgt innerhalb der EMMA-Informationsverwaltung. Die Wartung erfolgt nicht über die Entwickler, sondern über externe Dienstleister.
|===


== Kontextabgrenzung
Als Eingabeschnittstelle existieren verschiedene Eingabefelder auf der Website. Kunden können hier Produkte kaufen und ihr Rabattkonto einsehen. 
Mitarbeiter können über die Website Produktinformationen und Kunden-Daten einsehen und ändern. Zudem erhalten Mitarbeiter und Administratoren Einsicht in Bilanzen und Produktbestände sowie Mitarbeiter und Nutzer. 


== Lösungsstrategie
[options="header"]
|===
|Name |Beschreibung 
|Java |Zur Entwicklung wird Java 1.8 eingesetzt. 
|Spring | Zur besseren Entwicklung wird das Spring-Framework genutzt, welches u.a. bereits über Datenbankfunktionalitäten und Webausgabe verfügt.
|SalesPoint | Das SalesPoint-Framework ist auf Spring aufgesetzt und bietet eine große Bandbreite verschiedener Funktionen, die in einem Online-Shop benötigt werden.
|Bootstrap | Bootstrap ist ein CSS-Framework, welches verschiedene Gestaltungsvorlagen für das Front-End bereit hält. 
|Apache Maven | Maven ist ein Build-Management-Tool der Apache Software Foundation und basiert auf Java. Mit ihm kann man insbesondere Java-Programme standardisiert erstellen und verwalten.
|===

== Bausteinsicht
* Package-Diagramme

== Entwurfsentscheidungen
Im Backend gibt es folgende Module: 
- Login/Registrierung von Nutzern
- Katalog mit Warenübersicht und Detailansicht von Waren
- Warenkorb mit Kauffunktion
- Nutzerübersicht
- Waren-/Lagerbestand

Damit der Mitarbeiter neue Produkte hinzufügen kann, wird das Factory-Pattern genutzt. 
Das Singleton-Pattern wird für die gesamte Bilanz des Kaufhauses benutzt. 
Das Observer-Pattern garantiert die Benachrichtigung der Mitarbeiter, wenn ein Kommentar erstellt wird. 
In Sales Point werden Iterator- und MVC-Entwurfsmuster genutzt.
Falls das Internetkaufhaus in der Zukunft konfigurierbare Produkte anbietet, sollte das Deckorator-Pattern in Betracht bezogen werden.
Die Datenspeicherung erfolgt über die JPA-Datenbank, die mit Hilfe von Sales Point bearbeitet und ausgelesen wird. 

[appendix]
== Glossar
