= Test-Plan

Dieser Testplan stellt eine vereinfachte Version der IEEE 829-1998 Vorlage dar.

== Einführung
Der Testplan dient zur Organisation der Test am Softwareprodukt "Woods Super Dooper Shop" und gibt detailliert wieder, welche Kriterien bzw. Funktionalitäten erfolgreich getestet werden müssen.
Da mit dem Spring-Framework gearbeitet wird, bietet es sich an, die Tests in Unit-Tests und Integrations-Tests aufzuteilen. 
Während durch Unit-Tests einzelne Methoden getestet werden, wird bei Integration-Tests das komplette Modul getestet, vorrausgesetzt, alle Unit-Tests wurden erfüllt. 

== Aufbau der Testbezeichner
Die Tests sind nach folgendem Schema benannt:

U - Unit Test, I - Integrationstest, 1,2,3.. - Nummer, N - Überprüfung Normalfall, E - Überprüfung Fehlerfall, +

z.B.: "U-2-E" bedeutet 2. Unit-Test, der den Fehlerfall überprüft


== Test Gegenstände

== Zu testende Funktionalitäten
Die Methodenaufrufe innerhalb der einzelnen Klassen werden getestet. Das schließt die Methoden der Controller mit ein. 
Die Schnittstellen zu anderen Bibliotheken von Drittanbietern werden benfalls getestet, gleichermaßen die "Dependency Injection".

== Nicht zu testende Funktionalitäten
z.B. Bibliotheken von Drittanbietern (eigene Tests beschränken sich auf Schnittstelle, bzw. Zusammenspiel).

== Herangehensweise
Zuerst werden die Methoden/Schnittstellen/Verknüpfungen in den Klassen mit Hilfe von JUnit 4 getestet. Wenn diese Tests bestanden sind, wird das Modul , welches die Klassen enthält, getestet.
Also werden modulweise immer erst Unit-Tests und anschließend Integrations-Tests durchgeführt. Es wird innerhalb der Module das Bottem-Up-Testmuster verfolgt.

== Umgebungsvoraussetzungen
Vorraussetzung ür JUnit-Tests sind ein Maven-ausführbares System, auf dem eine Java-Entwicklungsumgebung läuft.
Es wird das Software-Entwicklungsprojekt benötigt, in welchem die Funktionalität getestet wird. 
Für die konkreten Test-Klassen wird ein seperater Ordner angelegt. Dieser wird dann mit hilfe von Maven ausgeführt bzw. getestet. 
Maven gibt durch Konsolenausgaben Infromationen bezüglich der Testverläufe zurück. 
Für das testen wird die JUnit-Bibliothek benötigt, außerdem werden mehrere Spring-Bibliotheken importiert. Gerade die Verknüpfungen durch die "Dependency Injection" sind hier zu beachten.
Für einige Tests, beispielsweise dem des E-Mail-Versendens wird eine anliegende Internetverbindung benötigt.

== Testfälle und Verantwortlichkeit
Jede testbezogene Aufgabe muss einem Ansprechpartner zugeordnet werden.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="headers"]
|===
|ID |Anwendungsfall |Vorbedingungen |Eingabe |erwartete Ausgabe |Implementierer |Tester
|U-1-N |ConcreteProduct: Test getName, Test Name-Parameter Konstruktor| - |Erstellen eines neuen ConcreteProduct-Objekts mit Name "Zigarre"|String "Zigarre" |Linda|Heiner
|U-1-E |ConcreteProduct: Test getName, Test Name-Parameter Konstruktor| - |Erstellen eines neuen ConcreteProduct-Objekts mit Name ""|Fehler, da Name leer (IllegalArgumentException) |Linda|Heiner
|U-..|..|..|..|..|..|..
|U-1..|Search: Test list50||||-|-
|U-2..|Search: Test addProds||||-|-
|U-3..|Search: Test delete||||-|-
|I-..|ShopController|-|-|-|-|-
|U-1-N..|ConcreteMailSender: Test sendMail|Internetanbindung, korrekt gesetzte application.properties|Mail mit Beispieldaten verschicken|Mail kommt bei gesetzter E-Mail-Adresse an|Heiner|Heiner
|I-..|CartController|||||
|U-..|Comment|-|-|-|Linda|-
|I-..|ManagementController|||||
|U-1-N..|ConcreteProductRepository: Test findByCategory|im Katalog befinden sich kategorisierte Produkte|übergib Kategorie und Anzahl an in der Page zu speichernden Produkten|Anzahl an Produkten mit gleicher Kategorie wird in Page gespeichert||
|I-..|CatalogController|||||
|U-1-N|AccountAdministration: Test requestKey|random-Funktion|E-Mail Adresse wird übergeben|Schlüssel mit Mail und zufällig generierter Zahl wird ausgegeben, Zufallszahl besitzt 32 Stellen|Lars|
|U-2-N|AccountAdministration: Test PassValidation|valider key aus requestKey-Methode, Mail-Sender|Key wird übergeben|Mail mit Registrierungs-Link wird abgeschickt|Lars|isValidKey
|U-3-N|AccountAdministration: Test isValidKey|key-Objekt|Key wird übergeben|Key wird auf Validität geprüft|Lars|
|U-0|ConcreteUserAccount|-|-|-|-|-
|U-1-N|ConcreteUserAccountManager|-|-|-|-|-
|I-..|AuthController|||||
|U-..|ConcreteUserAccountRepository: Test findByRole|Nutzer-Account mit zugewiesener Rolle|Rolle wird übergeben|Alle Nutzer mit entsprechender Rolle werden zurückgegeben|-|-
|I-..|AdminController|||||
|===
